name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest flake8-html pytest-html
        if (Test-Path requirements.txt) { pip install -r requirements.txt }
  lint:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install flake8 and flake8-html
      run: |
        python -m pip install flake8 flake8-html
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      continue-on-error: true
    - name: Lint with flake8 and generate HTML report
      run: |
        flake8 . --format=html --htmldir=flake-report
      continue-on-error: true
    - name: Upload flake8 report
      uses: actions/upload-artifact@v3
      with:
        name: flake8-report
        path: flake-report

  test:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-html
        if (Test-Path requirements.txt) { pip install -r requirements.txt }
    - name: Test with pytest
      run: pytest
      continue-on-error: true
    - name: Test with pytest and generate HTML report
      run: |
        pytest --html=pytest-report.html
      continue-on-error: true
    - name: Upload pytest report
      uses: actions/upload-artifact@v3
      with:
        name: pytest-report
        path: pytest-report.html
